sudo: false
language: node_js

# https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn
cache: yarn

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi

matrix:
  include:
    - node_js: 8
      env: BROWSERS=travis_chrome,Firefox
      os: linux
      dist: bionic
      services:
        - xvfb
      addons:
        firefox: latest
    - node_js: 8
      env: BROWSERS=sl_ie
      services:
        - xvfb
      addons:
        sauce_connect: true
      os: linux
      dist: bionic
    - node_js: 8
      env: BROWSERS=sl_edge
      services:
        - xvfb
      addons:
        sauce_connect: true
      os: linux
      dist: bionic
    - node_js: 8
      os: osx
      env: BROWSERS=Safari

script:
  - yarn test --browsers $BROWSERS

after_success:
  - if [[ -d coverage/ ]]; then cat coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js ; fi
